version: "3"
services:
  php:
    build: ./docker/app
    links:
      - mysql
      - redis
    volumes:
      - ./src:/var/data
      - ./data/logs/php:/var/log/php-fpm
    working_dir: /var/data/hr-internal
    container_name: "hr-internal-app"

  nginx:
    build: ./docker/web
    ports:
      - "80:80"
      - "8082:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./docker/web/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web/conf/hr_vhost.conf:/etc/nginx/conf.d/hr_vhost.conf
      - ./src:/var/data:cached
      - ./data/logs/nginx:/var/log/nginx
    container_name: "hr-internal-nginx"
  
  mysql:
    build: ./docker/db
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 63306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    container_name: "hr-internal-mysql"

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    container_name: "hr-internal-redis"
  
  nodejs:
    image: node:11
    container_name: "hr-internal-nodejs"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/var/data:cached
    working_dir: /var/data/hr-internal
    expose:
      - "8082"
    tty: true


